# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 10:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='check_day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(auto_now=True, verbose_name='签到日期')),
                ('checkin_time', models.DateTimeField(blank=True, null=True, verbose_name='签入时间')),
                ('checkout_time', models.DateTimeField(blank=True, null=True, verbose_name='签出时间')),
            ],
            options={
                'verbose_name': '签到',
                'verbose_name_plural': '签到管理',
            },
        ),
        migrations.CreateModel(
            name='god_sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='restdays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrecordmen', models.CharField(choices=[('周经纬', '周经纬'), ('陈茂华', '陈茂华'), ('曹强', '曹强'), ('李纯', '李纯')], max_length=20, verbose_name='登记人')),
                ('wweek', models.CharField(choices=[('星期一', '星期一'), ('星期二', '星期二'), ('星期三', '星期三'), ('星期四', '星期四'), ('星期五', '星期五'), ('星期六', '星期六'), ('星期日', '星期日')], max_length=20, verbose_name='星期')),
                ('wdate', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('wmen', models.CharField(max_length=50, verbose_name='加班人员')),
                ('wtimes', models.CharField(choices=[('1', '1天'), ('0.5', '0.5天')], max_length=20, verbose_name='加班时长')),
                ('wcontent', models.CharField(max_length=200, verbose_name='加班事项')),
            ],
            options={
                'verbose_name': '加班',
                'verbose_name_plural': '加班管理',
            },
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_year', models.DateField(default=django.utils.timezone.now, verbose_name='值班日期')),
                ('month', models.CharField(max_length=5, verbose_name='月份')),
                ('day', models.CharField(max_length=5, verbose_name='日')),
                ('date_flag', models.CharField(choices=[('0', '非交易日'), ('1', '交易日')], max_length=10, verbose_name='交易日')),
                ('west_day', models.CharField(choices=[('星期一', '星期一'), ('星期二', '星期二'), ('星期三', '星期三'), ('星期四', '星期四'), ('星期五', '星期五'), ('星期六', '星期六'), ('星期日', '星期日')], max_length=50, verbose_name='星期')),
                ('dule_group', models.CharField(blank=True, choices=[('A', 'A组'), ('B', 'B组'), ('C', 'C组'), ('D', 'D组')], max_length=24, null=True, verbose_name='值班小组')),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('show_times', models.CharField(max_length=5, verbose_name='周次数')),
            ],
            options={
                'verbose_name': '值班',
                'verbose_name_plural': '值班管理',
            },
        ),
        migrations.CreateModel(
            name='sys_dd_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dd_id', models.CharField(max_length=20, verbose_name='字段')),
                ('dd_item', models.CharField(max_length=5, unique=True, verbose_name='字段值')),
                ('dd_item_name', models.CharField(max_length=100, verbose_name='名称')),
            ],
            options={
                'verbose_name': '字典',
                'verbose_name_plural': '字典管理',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('user_code', models.IntegerField(verbose_name='代码')),
                ('user_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='用户类型 ')),
                ('user_group', models.CharField(blank=True, max_length=1, null=True, verbose_name='值班小组')),
                ('user_group2', models.CharField(blank=True, max_length=1, null=True, verbose_name='二线小组')),
                ('user_group_role', models.CharField(blank=True, max_length=5, null=True, verbose_name='组角色')),
                ('user_grade', models.IntegerField(blank=True, null=True, verbose_name='等级')),
                ('user_company', models.CharField(blank=True, max_length=30, null=True, verbose_name='所在公司')),
                ('user_role_id', models.IntegerField(blank=True, null=True, verbose_name='角色')),
                ('user_phone', models.IntegerField(blank=True, null=True, verbose_name='联系电话')),
                ('user_email', models.CharField(blank=True, max_length=20, null=True, verbose_name='邮箱')),
                ('user_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='籍贯')),
                ('user_pswd', models.CharField(blank=True, max_length=200, null=True, verbose_name='签到密码')),
                ('open_date', models.DateTimeField(auto_now=True, null=True, verbose_name='入职日期')),
                ('user_status', models.CharField(blank=True, max_length=1, null=True, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户管理',
            },
        ),
        migrations.AlterUniqueTogether(
            name='sys_dd_item',
            unique_together=set([('dd_id', 'dd_item')]),
        ),
        migrations.AddField(
            model_name='check_day',
            name='check_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='godbody.UserProfile', verbose_name='签到人'),
        ),
        migrations.AlterUniqueTogether(
            name='check_day',
            unique_together=set([('check_name', 'check_date')]),
        ),
    ]
