# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 13:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('my_mail', models.CharField(max_length=32, verbose_name='邮箱')),
                ('rank', models.CharField(max_length=32, verbose_name='级别')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('qq', models.CharField(blank=True, max_length=16, null=True, verbose_name='QQ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
