# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('godbody', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建日期')),
                ('announ_title', models.CharField(default='', max_length=100, verbose_name='主题')),
                ('context', models.CharField(max_length=300, verbose_name='公告内容')),
                ('exec_time', models.DateField(verbose_name='执行时间')),
                ('remark', models.CharField(blank=True, max_length=300, null=True, verbose_name='备注')),
                ('sign_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='godbody.UserProfile', verbose_name='登记人')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告管理',
            },
        ),
        migrations.CreateModel(
            name='channel_list',
            fields=[
                ('id_for_cha', models.IntegerField(primary_key=True, serialize=False, verbose_name='id号')),
                ('name_for_cha', models.CharField(max_length=100, verbose_name='渠道列表')),
            ],
            options={
                'verbose_name': '渠道列表',
                'verbose_name_plural': '渠道列表',
            },
        ),
        migrations.CreateModel(
            name='planshows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pstype', models.CharField(blank=True, max_length=10, null=True, verbose_name='计划类型')),
                ('pstime', models.CharField(blank=True, max_length=10, null=True, verbose_name='计划时间')),
                ('pstitle', models.CharField(blank=True, max_length=20, null=True, verbose_name='计划主题')),
                ('psinfo', models.TextField(blank=True, max_length=200, null=True, verbose_name='计划内容')),
                ('psremark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '计划任务',
                'verbose_name_plural': '计划任务',
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnum', models.CharField(max_length=50, verbose_name='编号')),
                ('pjira', models.CharField(max_length=30, verbose_name='jira编号')),
                ('pdate', models.DateField(default=django.utils.timezone.now, max_length=30, verbose_name='登记日期')),
                ('punit', models.CharField(choices=[('P0', '其他'), ('P1', '托管'), ('P2', '互联网金融大开户'), ('P3', '互联网金融独立开户'), ('P4', '互联网金融独立交易'), ('P5', '第三方'), ('P6', '上海运营部（内部）')], max_length=30, verbose_name='项目类型')),
                ('pname', models.CharField(max_length=30, verbose_name='项目名称')),
                ('pdoc', models.CharField(choices=[('D0', '其他'), ('D1', '全新项目'), ('D2', '追加渠道')], max_length=30, verbose_name='项目类别')),
                ('pallot', models.CharField(choices=[('周经纬', '周经纬'), ('陈茂华', '陈茂华'), ('曹强', '曹强')], max_length=30, verbose_name='派工人')),
                ('pmen', models.CharField(max_length=30, verbose_name='项目经理')),
                ('pnetmen', models.CharField(choices=[('高大海', '高大海'), ('崔飞', '崔飞'), ('孙志崴', '孙志崴')], max_length=30, verbose_name='平台人员')),
                ('ponliedate', models.DateField(verbose_name='上线日期')),
                ('pstatus', models.CharField(choices=[('0', '已验收'), ('1', '实施中'), ('2', '暂停'), ('3', '上线'), ('4', '关闭')], max_length=30, verbose_name='项目状态')),
                ('premark', models.CharField(max_length=30, verbose_name='备注')),
                ('p_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ez_qd', to='pypro.channel_list')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目管理',
            },
        ),
        migrations.CreateModel(
            name='secu_list',
            fields=[
                ('id_for_com', models.IntegerField(primary_key=True, serialize=False, verbose_name='id号')),
                ('name_for_com', models.CharField(max_length=100, verbose_name='券商')),
            ],
            options={
                'verbose_name': '券商列表',
                'verbose_name_plural': '券商列表',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='p_secu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ez_qs', to='pypro.secu_list'),
        ),
    ]
