# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('godbody', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bug_fault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_code', models.CharField(max_length=32, verbose_name='漏洞代码')),
                ('bug_name', models.CharField(max_length=32, verbose_name='漏洞名称')),
                ('bug_version', models.CharField(max_length=64, verbose_name='漏洞影响版本')),
                ('bug_synopsis', models.TextField(verbose_name='漏洞简介')),
                ('bug_harm', models.TextField(verbose_name='漏洞危害')),
                ('bug_repair_work', models.IntegerField(choices=[(1, '已完成'), (2, '未完成')], default=1, verbose_name='修复状况')),
                ('bug_register_time', models.DateField(verbose_name='记录时间')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('bug_registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='godbody.UserProfile', verbose_name='登记人')),
            ],
        ),
        migrations.CreateModel(
            name='god_bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('god_bug_date', models.DateTimeField(verbose_name='故障日期')),
                ('god_bug_type', models.IntegerField(choices=[(1, '系统'), (2, '应用'), (3, '网络')], default=2, verbose_name='影响类别')),
                ('god_bug_ip', models.CharField(blank=True, max_length=32, null=True, verbose_name='故障IP')),
                ('god_bug_phenomenon', models.TextField(verbose_name='故障现象')),
                ('god_bug_solve', models.TextField(blank=True, null=True, verbose_name='故障解决')),
                ('god_bug_track', models.TextField(blank=True, null=True, verbose_name='故障跟踪')),
                ('god_bug_remarks', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
                ('god_bug_registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='godbody.UserProfile', verbose_name='登记人')),
            ],
        ),
        migrations.CreateModel(
            name='Project_speed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_track', models.TextField(verbose_name='工作进度')),
                ('end_type', models.IntegerField(blank=True, choices=[(0, 'None'), (1, '已完工'), (2, '未完工')], default=0, null=True, verbose_name='完工状态')),
                ('Completion_date', models.DateField(blank=True, null=True, verbose_name='完成时间')),
                ('expect_date', models.DateField(blank=True, null=True, verbose_name='预期完成时间')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Projectpig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64, verbose_name='项目名')),
                ('work_content', models.TextField(verbose_name='工作内容')),
                ('open_date', models.DateField(verbose_name='开始时间')),
                ('end_type', models.IntegerField(blank=True, choices=[(0, 'None'), (1, '已完工'), (2, '未完工')], default=0, null=True, verbose_name='完工状态')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('person_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='godbody.UserProfile', verbose_name='负责人')),
            ],
        ),
        migrations.AddField(
            model_name='project_speed',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectpig.Projectpig', verbose_name='项目跟踪'),
        ),
        migrations.AddField(
            model_name='project_speed',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='godbody.UserProfile', verbose_name='跟踪人员'),
        ),
    ]
