# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_speed',
            name='end_type',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, '已完工'), (2, '未完工')], default=0, null=True, verbose_name='完工状态'),
        ),
    ]
