# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectpig', '0002_project_speed_end_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_speed',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
